### ISSUE TITLE
Ajouter analyse de couverture 

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/MBES-lib#119]
Ajouter une analyse de couverture des tests unitaires avec gcov et lcov au Makefile sous une cible appelée "coverage". On doit placer les fichiers de sortie et les rapports dans build/coverage, et publier 

@HugoValcourt et @EmileGagne travaillerez ensemble là-dessus: hugo monteras la pipeline (http://www.yolinux.com/TUTORIALS/Jenkins-Cpp-builds.html la partie sur gcov), 
et Émile s'occupera de la couverture manquante.

**Comment by HugoValcourt** [comment]
Parfait!

**Comment by EmileGagne** [comment]
Compris

**Comment by HugoValcourt** [comment]
@glabmoris Est-ce que le coverage devrais ce faire avec les tests ou ça devrais être une autre 'step' en sois?

**Comment by glabmoris** [comment]
Tu peux le faire en meme temps que les tests, ca va te donner 2 rapports (junit, et cobertura)
