### ISSUE TITLE
Identification de fichier

### ISSUE THREAD

**Issue by HugoValcourt** [CIDCO-dev/MBES-lib#133]
Il y a plusieurs fichier qui n'ont pas d'auteur associer.

SVP, identifier vos fichier pour la documentation de Doxygen.

Merci!

**Comment by glabmoris** [comment]
PS: Post les noms de fichiers sans auteur que tu trouves ici

**Comment by HugoValcourt** [comment]
Parfait

**Comment by HugoValcourt** [comment]
- https://github.com/CIDCO-dev/MBES-lib/tree/master/src/Raytracing.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/svp/SoundVelocityProfileFactory.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/math/Boresight.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/datagrams/DatagramParser.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/datagrams/DatagramParserFactory.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/datagrams/kongsberg/KongsbergTypes.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/utils/Constants.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/utils/TimeUtils.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/utils/StringUtils.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/filter/InsanePositionFilter.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/filter/IntensityFilter.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/filter/QualityFilter.hpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/cidco-decoder.cpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/cidco-decoder.cpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/data-cleaning.cpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/georeference.cpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/viewer/viewer.cpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/datagram-list.cpp
 - https://github.com/CIDCO-dev/MBES-lib/tree/master/src/examples/datagram-dump.cpp

**Comment by glabmoris** [comment]
LEs autres:
InsanePositionFilter,IntensityFilter sont de Emile Gagne

**Comment by HugoValcourt** [comment]
Merci
