### ISSUE TITLE
Tests Georef et raytracing

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/MBES-lib#146]
@CBcidco a trouvé un bogue dans le décodage de fichiers S7k (quai). Baliser le géoref par des tests, ainsi que le raytracing. 

- [ ] Creer un test unitaire pour GeoreferencingTRF::georeference(...)
- [ ] Creer un test unitaire pour GeoreferencingLGF::georeference(...)
- [ ] Creer un test unitaire pour Raytracing::raytrace(...)

**Comment by JordanMcManus** [comment]
Le géoref en TRF donne exactement le même résultat que le géoref en LGF.

**Comment by JordanMcManus** [comment]
Tu as un doublon pour GeoreferencingTRF::georeference(...). J'imagine que c'était LGF?

**Comment by JordanMcManus** [comment]
J'ai ajouté 2 tests, un pour le raytracing et un pour le géoref en LGF.

Il faut dire que le code de MBES-lib ne compilait pas, les tests ne passaient pas et les builds ont tous échoué avant que je commence à travailler la dessus. De plus, établir des valeurs de référence pour faire la comparaison a nécéssité beaucoup de calculs.

**Test pour le raytracing**

J'ai comparé le résultat de ton (@glabmoris ) ray tracing avec celui dans le code de Elliot pour le DataCleaning (avec lequel on voit bien le quay de Baie-Comeau).

J'ai fourni exactement les mêmes valeurs en entrée aux 2 fonctions et il y a une légère différence (8 millimètres) due au fait que le code d'Elliot prend en charge le draft alors que le tiens ne le considère pas.

**Test pour le géoréférencement dans le repère de navigation (LGF)**

Ibidem pour la comparaison entre la fonction de géoréférencement de Elliot et de Guillaume.

J'ai fourni exactement les mêmes valeurs en entrée aux 2 fonctions.
Pour la profondeur, il y a 5 centimètres de différence.
Toutefois, à l'horizontale c'est 26 mètres de différence! Donc, il y a de quoi à réparer la dedans.

**Comment by glabmoris** [comment]
Idem de mon côté, le géoreférencement directement au nadir marche correctement. Il va falloir voir si c'est l'attiutude ou le raytracing qui cloche
