### ISSUE TITLE
[s7k] Crash when parsing file

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/MBES-lib#217]
This looks like an aggravation of #27 

> glm@Omega:~/src/MBES-lib$ ./build/bin/georeference test/data/s7k/20170529_111841_Seabat.s7k 
> [+] No georeferencing method defined (-L or -T). Using TRF by default
> [+] Using nearest in time sound velocity profile selection strategy by default
> [+] Decoding test/data/s7k/20170529_111841_Seabat.s7k
> Checksum error
> Checksum error
> Checksum error
> Checksum error
> Checksum error
> ...
> [+] Using default SVP model
> [+] Position data points: 551 [1496056719500000 to 1496056774500000]
> [+] Attitude data points: 0 [Segmentation fault (core dumped)
>

**Comment by JordanMcManus** [comment]
Les checksum error sont causés par le record 7610 (7k Sound Velocity).

Donc, ce n'est pas un profil de célérité qui se trouve dans ce fichier, mais des données ponctuelles de vitesse du son.

De plus, il n'y a pas de données d'attitudes.
