### ISSUE TITLE
Can't decode starfish xtf data

### ISSUE THREAD

**Issue by JordanMcManus** [CIDCO-dev/MBES-lib#226]
Currently obtain segmentation fault when trying to decode starfish xtf data.

Probably need to add data structs to XtfParser.

**Comment by glabmoris** [comment]
I can confirm that this is not a missing datagram issue, it clearly contains the ID 0 datagrams for sidescan data. It does not contain position or attitude datagrams though. Just like the plane example

```
glm@Omega:~/src/MBES-lib$ ./build/bin/datagram-list test/data/xtf/plane-sidescan2d.xtf |sort|uniq -c
Decoding test/data/xtf/plane-sidescan2d.xtf
   2009 0
glm@Omega:~/src/MBES-lib$ ./build/bin/datagram-list test/data/xtfStarFish/22_07_2020_C1.xtf |sort|uniq -c
Decoding test/data/xtfStarFish/22_07_2020_C1.xtf
   3617 0
```

**Comment by glabmoris** [comment]
I can decode them perfectly using the latest version of opensidescan updated to the latest MBES-lib dependency.

![image](https://user-images.githubusercontent.com/9091120/88961573-37f38680-d273-11ea-8fe1-e9d02b2ece8a.png)

**Comment by glabmoris** [comment]
Closing this as a non-issue until it can be reproduced. Also, I'm going to leave a single XTF file as a starfish example only.

**Comment by JordanMcManus** [comment]
Nice!

I just realised I used georeference executable and that is why I got segfault.
