### ISSUE TITLE
Use draft in ray tracing and use SSS to calculate Snell's constant

### ISSUE THREAD

**Issue by JordanMcManus** [CIDCO-dev/MBES-lib#232]
Use draft (which is 4.3m for Deneb).

Jean-Guy indicates that Snell's constant should be calculated with SSS instead of SVP.

We can implement a strategy pattern for ray tracing since it is foreseeable that other strategies could be used (for example launch angle correction, SSS bias, etc.)

**Comment by glabmoris** [comment]
Logically, the SSS would be item 0 in a SVP. We could continue to use the SVP-driven logic by simply ensuring that the top element of the SVP's (depth, SS) pairs is (0,SSS). We would need to confirm that the SSS is actually measured at the surface, and not near the MBES, which is a depth=draft+some tiny Z offset.

What do you think ?

**Comment by JordanMcManus** [comment]
The sound velocity probe is installed next to the MBES transducer which is at 4.3m below surface.

The name Surface Sound Speed is an unfortunate misnomer used by manufacturer, they should have used Transducer Sound Speed instead.

Here's a picture of the probe next to the MBES that Jean-Guy sent:

![190620_DENEB_0040](https://user-images.githubusercontent.com/36419498/98018929-25876c80-1dcf-11eb-8bd5-1b6d1e489831.jpg)

**Comment by JordanMcManus** [comment]
Unless the probe is directly installed at the water line, it won't really be Surface Sound Speed.

**Comment by JordanMcManus** [comment]
I do agree that we could chop the SVP at the draft and inject the SSS at element 0 before doing the ray tracing.

**Comment by glabmoris** [comment]
If it's far in the upward direction, then it's irrelevant for raytracing. If it's further down from the transducer, it's a major wtf that's very unlikely to happen. I'd say we could safely assume that it's approximately where the transducer is, AKA depth = draft.

**Comment by JordanMcManus** [comment]
Sounds good to me!
