### ISSUE TITLE
Intégrer nouveaux éxécutables à pipeline

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/MBES-lib#66]
Intégrer la compilation des nouveaux programmes dans src/examples à la pipeline (datagram-list et georeference), incluant la génération d'éxécutables distribuables

**Comment by glabmoris** [comment]
Les éxécutables ne sont pas publiés sur le serveur apache pour que les utilisateurs puissent les télécharger.

**Comment by HugoValcourt** [comment]
Ok je regarde ça.
